---
extends: default

rules:
  line-length:
    max: 120
    level: error
  comments:
    min-spaces-from-content: 1
  indentation:
    spaces: 2
    indent-sequences: true
  brackets:
    max-spaces-inside: 1
  truthy:
    allowed-values: ["true", "false", "on", "off", "yes", "no"]

ignore: |
  .github/workflows/
  vendor/
  node_modules/
